export { default as Computer } from "./computer.svg"
export { default as Skills } from "./skills.svg"
export { default as Job } from "./job.svg"
export { default as Letter } from "./letter.svg"
export { default as Like } from "./like.svg"
export { default as Current } from "./curriculum.svg"
export { default as Myself } from "./igorphoto.png"
export { default as Projects } from "./project.svg"
